package Ticket;


import Epiccinema.frmMain;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author e'DON
 */
public class FoodAndBeverage extends javax.swing.JFrame {

    /**
     * Creates new form FoodAndBeverage
     */
    public FoodAndBeverage() {
        initComponents();
        FoodList.addItem("Pop Corn S");
        FoodList.addItem("Pop Corn M");
        FoodList.addItem("Pop Corn L");
        FoodList.addItem("Hot Dog S");
        FoodList.addItem("Hot Dog M");
        FoodList.addItem("Hot Dog L");
        FoodList.addItem("Sweet Corn S");
        FoodList.addItem("Sweet Corn M");
        FoodList.addItem("Sweet Corn L");

        
        
        BeverageList.addItem("Pepsi S");
        BeverageList.addItem("Pepsi L");
        BeverageList.addItem("Strawberry S");
        BeverageList.addItem("Strawberry L");
        BeverageList.addItem("Ice Lemon Tea S");
        BeverageList.addItem("Ice Lemon Tea L");
        BeverageList.addItem("Mineral Water S");
        BeverageList.addItem("Mineral Water L");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FoodList = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        BeverageList = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        NoFood = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        NoBeverage = new javax.swing.JTextField();
        TotalPrice = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        ResetButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PrintArea2 = new javax.swing.JTextArea();
        Print = new javax.swing.JToggleButton();
        backbtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Food :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Food and Breverage");

        FoodList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoodListActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Beverage");

        BeverageList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BeverageList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeverageListActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number:");

        NoFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoFoodActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number:");

        TotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalPrice.setText("Total");
        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total Price:        RM");

        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        PrintArea2.setColumns(20);
        PrintArea2.setRows(5);
        jScrollPane1.setViewportView(PrintArea2);

        Print.setText("Print");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FoodList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NoFood, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BeverageList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NoBeverage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TotalPrice)
                                .addGap(142, 142, 142)
                                .addComponent(ResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Print)
                        .addGap(18, 18, 18)
                        .addComponent(backbtn)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FoodList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(BeverageList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NoFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(NoBeverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalPrice)
                            .addComponent(ResetButton))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Print)
                            .addComponent(backbtn))
                        .addGap(27, 27, 27))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FoodListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoodListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoodListActionPerformed

    private void BeverageListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeverageListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeverageListActionPerformed

    private void NoFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoFoodActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
       
        float result,foodPrice, foodNum, foodTotal;
        String FoodPrice = (String)FoodList.getSelectedItem();
        switch (FoodPrice)
        {
            case "Pop Corn S":
            foodPrice=5;break;
            case "Pop Corn M":
            foodPrice=7;break;
            case "Pop Corn L":
            foodPrice=10;break;
            case "Hot Dog S":
            foodPrice=2;break;
            case "Hot Dog M":
            foodPrice=4;break;
            case "Hot Dog L":
            foodPrice=6;break;
            case "Sweet Corn S":
            foodPrice=1;break;
            case "Sweet Corn M":
            foodPrice=3;break;
            case "Sweet Corn L":
            foodPrice=5;break;
            default:
            foodPrice=0;
            break;
        }
    
    
       foodNum = Float.parseFloat(NoFood.getText());
    
       foodTotal = foodPrice * foodNum;
       
       float beveragePrice, beverageNum, beverageTotal;
        String BeveragePrice = (String)BeverageList.getSelectedItem();
        switch (BeveragePrice)
        {
            case "Pepsi S":
            beveragePrice=(float) 1.5;break;
            case "Pepsi L":
            beveragePrice=(float) 2.5;break;
            case "Strawberry S":
            beveragePrice=(float) 1.5;break;
            case "Strawberry L":
            beveragePrice=(float) 2.5;break;
            case "Ice Lemon Tea S":
            beveragePrice=2;break;
            case "Ice Lemon Tea L":
            beveragePrice=3;break;
            case "Mineral Water S":
            beveragePrice=1;break;
            case "Mineral Water L":
            beveragePrice=(float) 2.5;break;
            
            default:
            beveragePrice=0;
            break;
        }
       beverageNum = Float.parseFloat(NoBeverage.getText());
    
       beverageTotal = beveragePrice * beverageNum;
       result= beverageTotal+foodTotal;
    
       Price.setText(String.valueOf(result));
    }//GEN-LAST:event_TotalPriceActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.hide();
        frmMain info = new frmMain();
        frmMain.main(null);
    }//GEN-LAST:event_backbtnActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        NoFood.setText("");
        NoBeverage.setText("");
        Price.setText("");
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        PrintArea2.setText("*************************************************************************\n");
        PrintArea2.setText(PrintArea2.getText()+"                              To The Moon Cinema                   \n");
        PrintArea2.setText(PrintArea2.getText()+"*************************************************************************\n");
        PrintArea2.setText(PrintArea2.getText()+"                                                            Receipt                                                      \n");
        
        Date obj = new Date();
        String date = obj.toString();

        PrintArea2.setText(PrintArea2.getText()+"\nDate/Time Purchased :"+date+"\n\n");
        PrintArea2.setText(PrintArea2.getText()+"Purchased Food: "+FoodList.getSelectedItem()+" X "+  NoFood.getText()+"\n\n");
        PrintArea2.setText(PrintArea2.getText()+"Purchased Beverage: "+BeverageList.getSelectedItem()+" X "+  NoBeverage.getText()+"\n\n");
        PrintArea2.setText(PrintArea2.getText()+"Total Food and Beverage Price RM:"+   Price.getText() +"\n\n");

        try
        {
            PrintArea2.print();
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodAndBeverage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodAndBeverage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodAndBeverage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodAndBeverage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodAndBeverage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BeverageList;
    private javax.swing.JComboBox<String> FoodList;
    private javax.swing.JTextField NoBeverage;
    private javax.swing.JTextField NoFood;
    private javax.swing.JTextField Price;
    private javax.swing.JToggleButton Print;
    private javax.swing.JTextArea PrintArea2;
    private javax.swing.JToggleButton ResetButton;
    private javax.swing.JToggleButton TotalPrice;
    private javax.swing.JToggleButton backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
